api/urls.py
from django.urls import include, path
from rest_framework import routers

#from api.views.carrega_parceiros import ParceirosViewSet
from .views import *

router = routers.DefaultRouter()
#router.register(r'',views.controleParceiros)
router.register('parceiros', ParceirosViewSet, basename='Parceiros')
router.register('eventos', EventosViewSet, basename='Eventos')
router.register(r'doadores', DoadoresViewSet, basename="Doadores")
router.register(r'doacao', DoacaoViewSet, basename="Doacao")
router.register('blog', PostViewSet, basename='Blog')

urlpatterns = [
    # path('', views.getData),
    # path('add/', views.addData)
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

apps/cadastro/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'cadastro'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.mural_animais, name='mural_animais'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('form/', views.test_form, name='test_form'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elos_be/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
import parceiros

from elos_be.views import carrega_abrigo, carrega_home, carrega_index, carrega_contatos, carrega_ajuda, carrega_resgate, PaginaHome

from cadastro import views
from eventos import urls, views
from parceiros import urls, views
from doadores import urls, views 

from django.views.generic import TemplateView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import routers
from doadores.api import viewsets as doadoresviewsets

route = routers.DefaultRouter()

route.register(r'doadores', doadoresviewsets.DoadoresViewSet, basename="Doadores")
route.register(r'doacao', doadoresviewsets.DoacaoViewSet, basename="Doacao")

app_name = 'elos_be'
urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')), #ATIVAÇÃO DE RICH-TEXT
    path('', RedirectView.as_view(url='/elos/')),
    path('elos/', carrega_index, name="index"),
    path('elos/projeto', carrega_abrigo, name="projeto"),
    path('elos/contatos', carrega_contatos, name="contatos"),
    path('elos/ajuda', carrega_ajuda, name="ajuda"),
    path('elos/resgate', carrega_resgate, name="resgate"),
    path('elos/parceiros',include("parceiros.urls")),
    path('elos/eventos/', include("eventos.urls")),
    path('elos/mural_animais/', include("cadastro.urls")),
    path('elos/blog/', include("blog.urls")),
    path('elos/social/', include("rede_social.urls")),
    path('home/', PaginaHome.as_view(), name='home'),
    path('home2/', carrega_home, name='home2'),
    # path('home/', carrega_aplicacao, name="home"),
    path('', include("login_users.urls")),
    path('doadores', include("doadores.urls")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include(route.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    
]

apps/cadastro/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from djrichtextfield.models import RichTextField
from datetime import datetime, timedelta

data_atual = datetime.now()

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class EspecieAnimal(models.Model):
    especie = models.CharField(max_length=50,null=False,blank=False,unique=True,verbose_name='Espécie',help_text='Escreve a espécie do animal.')
    class Meta:
    #     db_table = 'especie' #nome definido da tabela no DB
        ordering = ['especie']
    def __str__(self): #correção para admin.py na aparecer como object
        return self.especie

class Document(models.Model):
    SEXO_ANIMAL = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        )
    TIPO_ANIMAL = (
        ('D', 'Doméstico'),
        ('S', 'Selvagem'),
        )
    PORTE_ANIMAL = (
        ('P', 'Pequeno'),
        ('M', 'Médio'),
        ('G', 'Grande'),
        )
    # docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    # docfile = models.FileField(upload_to='cadastro/media')
    docfile = models.FileField(upload_to='cadastro/media/%Y_%m_%d')
    nome_cachorro = models.CharField(max_length=30,verbose_name='Nome',help_text='Insira o nome do animal.')
    descricao = RichTextField(default='')
    sexo = models.CharField(null=True,max_length=1,choices=SEXO_ANIMAL, verbose_name='Sexo',help_text='Escolha o sexo do animal.')
    tipo = models.CharField(null=True,max_length=1,choices=TIPO_ANIMAL, verbose_name='Tipo',help_text='Escolha o tipo do animal.')
    porte = models.CharField(null=True,max_length=1,choices=PORTE_ANIMAL, verbose_name='Porte',help_text='Escolha o porte do animal.')
    data_nascimento = models.DateTimeField(null=True,verbose_name='Nascimento',help_text='Coloque a data aproximada de nascimento do animal.')
    especie = models.ForeignKey(EspecieAnimal,on_delete=models.CASCADE, blank=True, null=True, default=2)
    url = models.URLField(null=True,max_length=200)
    class Meta:
    #     db_table = 'mural_fofura' #nome definido da tabela no DB
        ordering = ['nome_cachorro','data_nascimento','tipo','porte']
    def __str__(self): #correção para admin.py na aparecer como object
        return self.nome_cachorro
    def get_idade(self):
        data_nascimento = self.data_nascimento
        idade = data_atual - data_nascimento
        if idade.days >= 365:
            return '%sY' %int(idade.days / 365)
        elif idade.days >= 30:
            return '%sM' %int(idade.days / 30)
        else:
            return '%sd' %idade.days
    def get_especie(self):
        busca_especie = list(self.especie.all())
        return busca_especie
    
    #def get_parceiros(self):
    #    busca_parceiros = list(self.parceiros.all())
    #    if busca_parceiros!=0:
    #        lista_parceiros = []
    #        arruma_lista = Parceiros()
    #        for arruma_lista in busca_parceiros:
    #            arruma_lista = arruma_lista.nome_parceiro
    #            lista_parceiros.append(arruma_lista)
    #        return lista_parceiros
    #    else:
    #        return False
    #def get_evento_recente(self):
    #    if self.data_evento >= data_atual:
    #        return True
    #    else:
    # pip install boto3 django-storages

apps/cadastro/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )
    nome = forms.CharField(label='Your name', max_length=100, help_text="Help text here")
    porte = forms.CharField(label='Your name', max_length=1, help_text="Help text here")
    idade = forms.IntegerField(label='Your name',help_text="Help text here")

apps/cadastro/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext
from django.urls import reverse
from django.views import generic

from .models import Choice, Question
from .models import Document, EspecieAnimal
from .forms import DocumentForm

# import datetime

class IndexView(generic.ListView):
    template_name = 'cadastro/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'cadastro/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'cadastro/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'cadastro/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('cadastro:results', args=(question.id,)))

# https://stackoverflow.com/questions/5871730/how-to-upload-a-file-in-django
def mural_animais(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile = request.FILES['docfile'],
                            nome_cachorro=request.POST["nome"],
                            porte_cachorro=request.POST["porte"],
                            idade_cachorro=request.POST["idade"],
                            # dia_do_cadastro=datetime.date.today()
                            )
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('cadastro:mural_animais'))
    else:
        form = DocumentForm() # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()
    especies = EspecieAnimal.objects.all()

    # Render list page with the documents and the form
    return render(request,
        'cadastro/form.html',
        {'documents': documents,'especies': especies,'form': form})

apps/cadastro/templates/cadastro/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Univesp PI - Polo Jacana</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/main.css' %}">
  </head>
  <body>
    <div class="container">      
      <h1>Esta é o piloto de PI da Univesp do grupo do Polo Jaçanã!</h1>
      <h2>O cadastro dos pets a serem adotados na ong se encontram abaixo</h2>

      {% block content %}
      {% endblock %}
    </div>


    
    <script src="{% static 'cadastro/ootstrap.min.js' %}">

  </body>
</html>

apps/cadastro/templates/cadastro/detail.html
{% extends 'cadastro/base.html' %}

{% block content %}

<form action="{% url 'cadastro:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Entra">
</form>

{% endblock %}

apps/cadastro/templates/cadastro/form copy.html
{% extends 'templates/../model-page.html' %}
{% load static %}

{% block content %}
<!-- Início do Cabeçalho -->
<div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
  <div class="col-auto">
    <img class="univesp-kaotinho img-fluid rounded mx-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/evento2.svg" alt="Univesp e Kaotinho" width="90px">
  </div>
  <div class="col-md-8 text-white">
    <h2 class="display-5 font-italic">Mural Fofura</h1>
    <p class="lead">Confira os animais para adoção.</p>
  </div>
</div><!-- Fim do cabeçalho-->
<!-- Conteúdo Principal -->
<div class="row justify-content-center">
    <div class="col-md-8 border-secondy">
        <!-- Aba das espécie de animais -->
        <ul class="nav nav-tabs border-secondy" id="myTab" role="tablist">
            {% for especie in especies %}
            <li class="nav-item" role="presentation">
                <button class="nav-link {% if especie.get_cachorro %} active {% endif %}" id="{{ especie.especie.lower }}-tab" data-bs-toggle="tab" data-bs-target="#{{ especie.especie.lower }}" type="button" role="tab" aria-controls="{{ especie.especie.lower }}" aria-selected="true">{{ especie.especie }}</button>
            </li>
            {% endfor %}
        </ul><!-- Fim da Aba das especies de animais -->
        <!-- Início do conteúdo do mural de cada espécie -->
        <div class="tab-content p-3 border-secondary shadow" id="myTabContent">
            {% for especie in especies %}
            <div class="tab-pane fade {% if especie.get_cachorro %}show active{% endif %} justify-content-between" id="{{ especie.especie.lower }}" role="tabpanel" aria-labelledby="{{ especie.especie.lower }}-tab">
                <div class="row justify-content-center m-1">
                    <div class="col-md-8">
                        {% if documents %}
                        {% for document in documents %}
                        <div class="card mb-3 col-6" style="max-width: 540px;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="{{ document.docfile.url }}" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <div class="row card-header bg-secondary align-middle text-white">
                                            <div class="col-12">
                                                <span class="material-icons align-middle fs-5">celebration</span>
                                                <span class="align-middle card=title fs-5">{{ document.nome_cachorro }}</span>
                                            </div>
                                        </div>
                                        <div class="row card-text text-muted">
                                            <div class="col-4">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-ambiguous" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M11.5 1a.5.5 0 0 1 0-1h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-3.45 3.45A4 4 0 0 1 8.5 10.97V13H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V14H6a.5.5 0 0 1 0-1h1.5v-2.03a4 4 0 1 1 3.471-6.648L14.293 1H11.5zm-.997 4.346a3 3 0 1 0-5.006 3.309 3 3 0 0 0 5.006-3.31z"/></svg>
                                                {{ document.sexo }}
                                            </div>
                                            <div class="col-4">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rulers" viewBox="0 0 16 16"><path d="M1 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h5v-1H2v-1h4v-1H4v-1h2v-1H2v-1h4V9H4V8h2V7H2V6h4V2h1v4h1V4h1v2h1V2h1v4h1V4h1v2h1V2h1v4h1V1a1 1 0 0 0-1-1H1z"/></svg>
                                                {{ document.porte }}
                                            </div>
                                            <div class="col-4">
                                                <svg class="fs-6" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16"><path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/></svg>
                                                {{ document.get_idade }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <span class="material-icons fs-6">description</span>
                                                <p class="card-text">{{ document.descricao }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <a class="btn btn-secondary" href="{{ document.url }}" role="button" target="_blank">Confira!</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="card mb-3 col-6" style="max-width: 540px;">
                            <div class="row g-0">
                                <div class="col-md-4">
                                    <img src="{{ document.docfile.url }}" class="img-fluid rounded-start" alt="...">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <div class="row card-header bg-secondary align-middle text-white">
                                            <div class="col-12">
                                                <span class="material-icons align-middle fs-5">celebration</span>
                                                <span class="align-middle card=title fs-5">{{ document.nome_cachorro }}</span>
                                            </div>
                                        </div>
                                        <div class="row card-text text-muted">
                                            <div class="col-4">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gender-ambiguous" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M11.5 1a.5.5 0 0 1 0-1h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-3.45 3.45A4 4 0 0 1 8.5 10.97V13H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V14H6a.5.5 0 0 1 0-1h1.5v-2.03a4 4 0 1 1 3.471-6.648L14.293 1H11.5zm-.997 4.346a3 3 0 1 0-5.006 3.309 3 3 0 0 0 5.006-3.31z"/></svg>
                                                {{ document.sexo }}
                                            </div>
                                            <div class="col-4">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rulers" viewBox="0 0 16 16"><path d="M1 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h5v-1H2v-1h4v-1H4v-1h2v-1H2v-1h4V9H4V8h2V7H2V6h4V2h1v4h1V4h1v2h1V2h1v4h1V4h1v2h1V2h1v4h1V1a1 1 0 0 0-1-1H1z"/></svg>
                                                {{ document.porte }}
                                            </div>
                                            <div class="col-4">
                                                <svg class="fs-6" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16"><path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/></svg>
                                                {{ document.get_idade }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <span class="material-icons fs-6">description</span>
                                                <p class="card-text">{{ document.descricao }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-12">
                                                <a class="btn btn-secondary" href="{{ document.url }}" role="button" target="_blank">Confira!</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div><!-- Fim do conteúdo do mural de cada espécie -->
    </div>
</div><!-- Fim do Conteúdo principal -->
{% endblock %}

apps/cadastro/templates/cadastro/form2.html
{% extends 'templates/../model-page.html' %}

{% block content %}

<section>
    <h2>Mural Fofura</h2>
    <article>Mural de adoção e apadrinhamento de animais.</article>
    <article>Curta! Compartilhe!</article>
</section>

    <!-- List of uploaded documents -->
    {% if documents %}
        <ul>
        {% for document in documents %}
        <section class="bloco-conteudo">
            <ul>
                <li><img class="rounded-circle" width="300px" src="{{ document.docfile.url }}"><br>
                    Nome do cachorro: {{ document.nome_cachorro }}
                    Porte do cachorro: {{ document.porte_cachorro }}
                    Idade do cachorro: {{ document.idade_cachorro }}
                </li>
            </ul>
        </section>
        {% endfor %}
        </ul>
    {% else %}
    <section class="bloco-conteudo">
        <p>No documents.</p>
    </section>

    {% endif %}

    <!-- Upload form. Note enctype attribute! -->
<!--    <form action="{% url 'cadastro:mural_animais' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        <p>Nome do cachorro: {{ form.nome }}</p>
        <p>Porte do cachorro (P, M, G): {{ form.porte }}</p>
        <p>Idade do cachorro: {{ form.idade }}</p>
        <p><input type="submit" value="Upload" /></p>
    </form>-->


{% endblock %}

apps/cadastro/templates/cadastro/index.html
{% extends 'cadastro/base.html' %}

{% block content %}

    <h2> Sugestão #1 - Sistema de cadastro para reciclagem </h2>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'cadastro:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}

{% endblock %}

apps/cadastro/templates/cadastro/results.html
{% extends 'cadastro/base.html' %}

{% block content %}

<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} => quantidade{{ choice.votes|pluralize }} = {{ choice.votes }}</li>
{% endfor %}
</ul>

<a href="{% url 'cadastro:detail' question.id %}">Cadastre mais deste tipo de material?</a>
<br>
<a href="{% url 'cadastro:index' %}">Cadastre mais produtos?</a>

{% endblock %}