api/urls.py
from django.urls import include, path
from rest_framework import routers

#from api.views.carrega_parceiros import ParceirosViewSet
from .views import *

router = routers.DefaultRouter()
#router.register(r'',views.controleParceiros)
router.register('parceiros', ParceirosViewSet, basename='Parceiros')
router.register('eventos', EventosViewSet, basename='Eventos')
router.register(r'doadores', DoadoresViewSet, basename="Doadores")
router.register(r'doacao', DoacaoViewSet, basename="Doacao")
router.register('blog', PostViewSet, basename='Blog')

urlpatterns = [
    # path('', views.getData),
    # path('add/', views.addData)
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

apps/doadores/urls.py
from django.urls import path
from django.conf.urls import url
from doadores import views

from .views import DoadoresList, DoacaoList, DoadoresUpdate, AtualizacaoDoadorCreate, DoacaoCreate
from django.contrib.auth import views as auth_views

# app_name = "doadores"


urlpatterns = [

    url(r'^doador/$', views.doadoresApi),
    url(r'^doador/([0-9]+)$', views.doadoresApi),
    path('novadoacao/', DoacaoCreate.as_view(), name='novadoacao'),
    path('listar/', DoadoresList.as_view(), name='listar'),
    path('ldoacao/', DoacaoList.as_view(), name='ldoacao'),
    path('formup/', DoadoresUpdate.as_view(), name='formup'),
    path('formc/', AtualizacaoDoadorCreate.as_view(), name='formc'),
]

elos_be/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
import parceiros

from elos_be.views import carrega_abrigo, carrega_home, carrega_index, carrega_contatos, carrega_ajuda, carrega_resgate, PaginaHome

from cadastro import views
from eventos import urls, views
from parceiros import urls, views
from doadores import urls, views 

from django.views.generic import TemplateView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import routers
from doadores.api import viewsets as doadoresviewsets

route = routers.DefaultRouter()

route.register(r'doadores', doadoresviewsets.DoadoresViewSet, basename="Doadores")
route.register(r'doacao', doadoresviewsets.DoacaoViewSet, basename="Doacao")

app_name = 'elos_be'
urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')), #ATIVAÇÃO DE RICH-TEXT
    path('', RedirectView.as_view(url='/elos/')),
    path('elos/', carrega_index, name="index"),
    path('elos/projeto', carrega_abrigo, name="projeto"),
    path('elos/contatos', carrega_contatos, name="contatos"),
    path('elos/ajuda', carrega_ajuda, name="ajuda"),
    path('elos/resgate', carrega_resgate, name="resgate"),
    path('elos/parceiros',include("parceiros.urls")),
    path('elos/eventos/', include("eventos.urls")),
    path('elos/mural_animais/', include("cadastro.urls")),
    path('elos/blog/', include("blog.urls")),
    path('elos/social/', include("rede_social.urls")),
    path('home/', PaginaHome.as_view(), name='home'),
    path('home2/', carrega_home, name='home2'),
    # path('home/', carrega_aplicacao, name="home"),
    path('', include("login_users.urls")),
    path('doadores', include("doadores.urls")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include(route.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    
]

apps/doadores/models.py
import re
from requests import request
from audioop import reverse
from faulthandler import disable
from pickle import TRUE
from statistics import mode

from django import forms
from django.conf import Settings, settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin

from localflavor.br.models import BRStateField, BRPostalCodeField, BRCPFField

# Create your models here.

class Doadores(models.Model):
    username = models.OneToOneField(User, on_delete=models.PROTECT, null= False, verbose_name='Doador',unique=True)
    dt_nasc = models.DateField(max_length=11,verbose_name='Data de Nascimento',help_text='Insira data de nascimento')
    celular = models.CharField(max_length=16, verbose_name='Celular para Contato',help_text='Insira o número de telefone',unique=True)
    cpf = BRCPFField(verbose_name='CPF',help_text='Cadastro de Pessoa Física',max_length=11)
    cep = BRPostalCodeField(max_length=9, verbose_name='CEP',help_text='Insira o CEP')
    endereco = models.CharField(max_length=500, verbose_name='Endereço',help_text='Insira o endereço')
    numero = models.IntegerField(verbose_name='Numero',help_text='Insira o número do endereço')
    complemento = models.CharField(max_length=50,verbose_name='Complemento',help_text='Insira o complemento do endereço')
    bairro = models.CharField(max_length=500, verbose_name='Bairro',help_text='Insira o bairro')
    cidade = models.CharField(max_length=500, verbose_name='Cidade',help_text='Insira a cidade')
    estado = BRStateField(null=True, blank=True, verbose_name='Estado',help_text='Insira o estado')
    local_referencia = models.CharField(max_length=50,verbose_name='Local de referência',help_text='Local de referência para facilitar a localização')

    class Meta:
        verbose_name = 'Doador'
        verbose_name_plural = 'Doadores'
        ordering = ['username',]

    def __str__(self):
        return "{}".format(self.username.get_full_name())
    def get_absolute_url(self):
        return reverse_lazy('home')

class Classificacao(models.Model):
    sintetica = models.CharField(verbose_name='Classificação Sintética',help_text='Digite a classificação sintética',max_length=30,null=False,blank=False)
    analitica = models.CharField(verbose_name='Classificação Analítica',help_text='Digite a classificação analítica',max_length=50,null=False,blank=False)
    class Meta:
        verbose_name = 'Classificação'
        verbose_name_plural = 'Classificações'
        ordering = ['sintetica','analitica']
        unique_together = [['sintetica','analitica']]
    def __str__(self):
        return f"{self.sintetica}: {self.analitica}"

re_matricula = re.compile('[a-zA-z]{4}-[0-9]{6}')

class Doacao(models.Model):

    DO = 'DOAR' #'DOADOR'
    DT = 'RECEBER'     #'DONATÁRIO'
                          
    intencao = (
        (DO, 'DOAR'),
        (DT, 'RECEBER')         
    )
    
    AL = 'ALIMENTOS NÃO PERECÍVEIS'
    AN = 'ANIMAIS'
    BR = 'BRINQUEDOS'
    EQ = 'EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)'
    HP = 'ITENS DE HIGIENE PESSOAL'
    LV = 'LIVROS'
    MV = 'MOVÉIS'
    RP = 'ROUPAS COMUM'
    RPC = 'ROUPAS DE FRIO E ACESSÓRIOS'
                               
    classificacao = (
        (AL, 'ALIMENTOS NÃO PERECÍVEIS'),
        (AN, 'ANIMAIS'),
        (BR, 'BRINQUEDOS'),
        (EQ, 'EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)'),
        (HP, 'ITENS DE HIGIENE PESSOAL'),
        (LV, 'LIVROS'),
        (MV, 'MOVÉIS'),
        (RP, 'ROUPAS COMUM'),
        (RPC, 'ROUPAS DE FRIO E ACESSÓRIOS')
    )

    NV = 'NOVO'
    SM = 'SEMI-NOVO'
    US = 'USADO'
    NA = 'NAO SE APLICA AO ITEM'

    listestado = (
        (NV, 'NOVO'),
        (SM, 'SEMI-NOVO'),
        (US, 'USADO'),
        (NA, 'NÃO SE APLICA')
    )
    
    publicar = models.BooleanField(verbose_name='Publicar?',help_text='O donativo deve ser publicado na página de doações?',default=False)
    matricula = models.CharField(verbose_name='Número de matricula',help_text='Insira o número de matricula conforme exemplo: AAAA-999999',max_length=11,
        blank=True)
    status = models.CharField(verbose_name='Status',help_text='Qual situação o donativo se encontra?',
        null=False,blank=False,max_length=4,default='CDOA',
        choices=[
            ('DOADOR',(
                ('CDOA','COM DOADOR'),
                ('ADOA','AGUARDANDO ENTREGA DO DOADOR'),)),
            ('RECEPTOR',(
                ('CREC','COM RECEPTOR'),
                ('AREC','AGUARDANDO RETIRADA DO RECEPTOR'),)),
            ('MANUTENÇÃO',(
                ('MREP','NECESSITANDO REPARO'),
                ('MPEC','AGUARDANDO PEÇA'),
                ('MHIG','EM HIGIENIZAÇÃO'),)),
            ('PROJETO',(
                ('PDOC','DISPONÍVEL PARA DOAÇÃO'),
                ('POBS','OBSOLETO'),)),
            ('UNKN','UNKNOWN'),
        ])
    descricao = models.CharField(max_length=3000, verbose_name='Donativo',help_text='Escreva o nome do item')
    intencao =  models.CharField(choices=intencao, verbose_name="Intenção do Donativo",help_text='Qual a intenção do donativo?',max_length=50)
    tamanho = models.CharField(verbose_name='Tamanho',help_text='Qual o tamanho do item?',
        null=False,blank=False,max_length=1,default='P',
        choices=[
            ('P','PEQUENO'),
            ('M','MÉDIO'),
            ('G','GRANDE'),
        ])
    detalhamento = models.TextField(verbose_name='Detalhamento',help_text='Escreva um detalhamento do donativo',
        max_length=250,null=False,blank=False)
    classificacao = models.ForeignKey(Classificacao,verbose_name='Classificação',help_text='Escolha a classificação do item',
        on_delete=models.PROTECT,null=False,blank=False)
    estado =  models.CharField(choices=listestado, verbose_name="Estado de Conservação", help_text='Qual o estado de conservação do item?',max_length=50)
    quantidade = models.IntegerField(verbose_name='Quantidade de Itens', null=False)
    username = models.ForeignKey(User, on_delete=models.PROTECT, null=False, verbose_name='Doador' )

    class Meta:
        verbose_name = 'Donativo'
        verbose_name_plural = 'Donativos'
        ordering = ['descricao',]

    def __str__(self):
        return "({}) {} {}".format(self.matricula,self.descricao,self.username.get_full_name())
    def get_absolute_url(self):
        return reverse('novadoacao')

class Receptor(models.Model):
    donativo = models.ForeignKey(Doacao,verbose_name='Donativo',help_text='Escolho o donativo',
        on_delete=models.PROTECT,null=False,blank=False)
    mensagem = models.CharField(verbose_name='Mensagem Elos de Amos',help_text='Status da Mensagem',
        null=False,blank=False,max_length=4,default='RECP',
        choices=[
            ('RECP','RECEPTOR ENVIOU'),
            ('DOAR','DOADOR RECEBEU'),
        ])
    status_contrato = models.CharField(verbose_name='Status',help_text='Doador assinou e devolveu o contrato?',
        null=False,blank=False,max_length=3,default='RECP',
        choices=[
            ('ASS','ASSINADO'),
            ('DEV','DEVOLVIDO'),
        ])
    data_vigencia = models.DateField(verbose_name='Data',help_text='Data de vigência do contrato')
    receptor = models.ForeignKey(User,on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Contrato'
        verbose_name_plural = 'Contratos'
    
    def __str__(self):
        return "{} {} {}".format(self.donativo.matricula,self.status_contrato,self.mensagem)

api/views/doadores.py
from rest_framework import viewsets
from api.serializers import doadores
from doadores import models

class DoadoresViewSet(viewsets.ModelViewSet):
    serializer_class = doadores.DoadoresSerializer
    queryset = models.Doadores.objects.all()

class DoacaoViewSet(viewsets.ModelViewSet):
    serializer_class = doadores.DoacaoSerializer
    queryset = models.Doacao.objects.all()

apps/doadores/views.py
from django.forms import ValidationError
from django.shortcuts import render
from django.shortcuts import get_object_or_404  
from django.contrib.auth.models import User, Group
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.http.response import JsonResponse
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import TemplateView
from .models import Doacao, Doadores
from doadores.serializers import DoadoresSerializer
from django.http import HttpResponse
from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

#class Doadores_rest(GroupRequiredMixin, LoginRequiredMixin):
 #   login_url = reverse_lazy('login')
 #   group_required = u"doadores"
 #   model = Doadores
 #   fields = ['nome', 'sobrenome', 'dt_nasc', 'endereco', 'numero', 'complemento', 'celular', 'Intencao']
 
 #   template_name = 'doadores/form.html'
    
@csrf_exempt

def doadoresApi(request, id=0):
    if request.method=="GET":
        doadores = Doadores.objects.all()
        doadores_serializer = DoadoresSerializer(doadores, many=True)
        return JsonResponse(doadores_serializer.data, safe=False)
    elif request.method=="POST":
        doador_data = JSONParser().parse(request)
        doador_serializer = DoadoresSerializer(data=doador_data)
        if doador_serializer.is_valid():
            doador_serializer.save()
            return JsonResponse("Cadastro realizado com sucesso!!!", safe=False)
        return JsonResponse("Ocorreu um erro durante a gravação dos dados, tente novamente", safe=False)

    elif request.method=="PUT":
        doador_data = JSONParser().parse(request)
        doador = Doadores.objects.get(id_doadores=doador_data['id_doadores'])
        doador_serializer = DoadoresSerializer(doador, data=doador_data)
        if doador_serializer.is_valid():
            doador_serializer.save()
            return JsonResponse("Atualização realizada com sucesso!!!!!!", safe=False)
        return JsonResponse("Falha na atualização do cadastro", safe=False)

    elif request.method=="DELETE":
        doador = Doadores.objects.get(id_doadores=id)
        doador.delete()
        return JsonResponse("Cadastro cancelado com Sucesso!!!", safe=False)

class DoadoresList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = u"admin"
    model = Doadores
    template_name = 'doadores/listas_doadores.html'

class DoacaoList(GroupRequiredMixin, LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    group_required = u"Doadores"
    model = Doacao
    queryset = Doacao.objects.filter(publicar=True)
    #.values_list('intencao')
    template_name = 'doadores/listas_doacao.html'
    #queryset = Doacao.objects.all()

    #def get_queryset(self):
     #   self.object_list = Doadores.objects.filter(username=self.request.user)
      #  return self.object_list

#do = DoacaoList()

## Model registrar

class DoadoresCreate(LoginRequiredMixin,GroupRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Doadores"
    model = Doadores
    fields = ['nome', 'sobrenome', 'dt_nasc', 'cep', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'celular', 'Intencao']
    template_name = "doadores/formdoadores.html"
    sucess_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Doadores, username=self.request.user)
        return self.object

    def form_valid(self, form):
        form.instance.username = self.request.user
        url = super().form_(form)
        return url

class DoacaoCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Doacao
    fields = ['intencao','classificacao', 'descricao', 'estado','tamanho','detalhamento','quantidade']
    template_name = "doadores/formdoacao.html"
    sucess_url = reverse_lazy('novadoacao')
    success_message = 'Obrigado(a) pela sua doação, com pequenas ações fazemos a diferença. DEUS te abençõe!!'

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Doacao, username=self.request.user)
        return self.object

    def form_valid(self, form):
        form.instance.username = self.request.user
        url = super().form_valid(form)
        return url 



## Atualizar dados de Colaborador 

class DoadoresUpdate(UpdateView, GroupRequiredMixin):
    login_url = reverse_lazy('login')
    group_required = u"Doadores"
    model = Doadores
    fields = ['dt_nasc', 'cep', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'celular']
    template_name = 'doadores/formdoadores.html'
    sucess_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(Doadores, username=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Registro de Novo Colabordor"
        context['Botao'] = "Atualizar"

        return context

class AtualizacaoDoadorCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Doadores
    fields = ['dt_nasc', 'cep', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'celular']
    template_name = 'doadores/formdoadores.html'
    success_url = reverse_lazy('home')
    
    def get_object(self, queryset=None):
        self.object = get_object_or_404(Doadores, username=self.request.user)
        return self.object

    def form_valid(self, form):
        form.instance.username = self.request.user
        url = super().form_valid(form)
        return url 

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Registro de Novo Colabordor"
        context['Botao'] = "Atualizar"

        return context

apps/doadores/templates/doadores/form copy.html
{% extends 'templates/../home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Cadastro{% endblock %}

{% block conteudo %}
    <h3>Cadastro de Doador</h3>
<p class="lead">
    Preencha todos os campos obrigatórios
</p>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <hr>

        <button class="btn btn-success" type="submit">Cadastrar</button>
    </form>

    {% endblock %}s %}

{% block scripts %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>

$(document).ready(function () {

$("#id_dt_nasc").mask("00/00/0000");
var SPMaskBehavior = function (val) {
    return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
},
    spOptions = {
        onKeyPress: function (val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
    };

$('#id_celular').mask(SPMaskBehavior, spOptions);

});

</script>
{% endblock %}

apps/doadores/templates/doadores/form.html
<style>


    .tableContainer{
        overflow-x: auto;
    }

    .fullTable{
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        border-collapse: collapse;
        width: 100%;
        text-align: center;      
        text-transform: capitalize; 
    }

    .fullTable td, .fullTable th{
        border: 1px solid #ddd;
        padding: 8px;
    }
    
    .fullTable th{
        background-color: #ba9eafed;
        color: white;
    }

    .fullTablen tr:nth-child(even){
        background-color: rgb(0, 0, 0);
    }

    .fullTable tr:hover{
        background-color: #ddd;
    }

</style>

{% extends 'templates/../model-page.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">
<!-- Cabeçalho da página -->
  <div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
    <div class="col-auto">
      <img class="univesp-elos img-fluid rounded mx-auto my-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/evento2.svg" alt="Logo balões de festa Univesp e Elos de Amor" width="90px">
    </div>
    <div class="col-md-8 text-white">
      <h2 class="display-5 font-italic">Doadores</h1>
      <p class="lead">Veja os doadores.</p>
    </div>
  </div><!-- Fim do cabeçalho -->
<!-- Conteúdo Principal -->
  <div class="row justify-content-center mt-0">
    <div class="col-md-12 border-secondy justify-content-start">
        <div class="col-md-8 mx-auto">

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
        
                <hr>
        
                <button class="btn btn-secondary" type="submit">Cadastrar</button>
            </form>

        </div>
    </div><!-- Fim row-->
  </div><!-- Fim do Conteúdo principal -->

</div>

{% endblock %}

<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>

$(document).ready(function () {

$("#id_dt_nasc").mask("00/00/0000");
var SPMaskBehavior = function (val) {
    return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
},
    spOptions = {
        onKeyPress: function (val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
    };

$('#id_celular').mask(SPMaskBehavior, spOptions);

});
</script>

apps/doadores/templates/doadores/formdoadores copy.html
{% extends 'templates/../home.html' %}

{% load static %}

{% load crispy_forms_tags %}


{% block conteudo %}
<h3>Cadastro de Colaboradores</h3>

<p class="lead">
    Preencha todos os campos obrigatórios.
</p>

<link href="https://piunivesp.s3.sa-east-1.amazonaws.com/elos_de_amor/media/logo-elos_transparente.png"
    rel="shortcut icon" type="image/x-icon" />


<form action="" method="POST">

    {% csrf_token %}

    <div class="form-row">
        <div class="form-group col-sm-5 sm-0">{{ form.nome|as_crispy_field }}</div>
        <div class="form-group col-sm-6 sm-0">{{ form.sobrenome|as_crispy_field }}</div>
        <div class="form-group col-sm-4 md-0">{{ form.dt_nasc|as_crispy_field }}</div>
    </div>

    <p class="lead">
    <h4>Endereço</h4>
    <div class="form-row">

    </div>

    <div class="form-row">
        <div class="form-group col-md-3 md-0"> {{ form.cep|as_crispy_field }}</div>
        <div class="form-group col-md-8 md-0"> {{ form.endereco|as_crispy_field }}</div>
        <div class="form-group col-md-3 md-0">{{ form.numero|as_crispy_field }}</div>
        <div class="form-group col-md-6 md-0">{{ form.complemento|as_crispy_field }}</div>
        <div class="form-group col-sm-3 sm-0">{{ form.bairro|as_crispy_field }}</div>
        <div class="form-group col-md-3 md-0">{{ form.cidade|as_crispy_field }}</div>
        <div class="form-group col-md-4 md-0">{{ form.estado|as_crispy_field }}</div>
    </div>

    <hr>

    <p class="lead">
    <h4>Dados Gerais</h4>
    </p>

    <hr>

    <div class="form-row">
        <div class="form-group col-md-3 md-0">{{ form.celular|as_crispy_field }}</div>
        <div class="form-group col-md-4 md-0">{{ form.Intencao|as_crispy_field }}</div>
        
    </div>

    <button type="submit" class="btn btn-success">Registrar</button>

</form>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://unpkg.com/imask@6.0.7/dist/imask.js"></script>


<script>
    $(document).ready(function () {

        $("#id_dt_nasc").mask("00/00/0000");
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_celular').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock scripts %}

<style>


    .tableContainer{
        overflow-x: auto;
    }

    .fullTable{
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        border-collapse: collapse;
        width: 100%;
        text-align: center;      
        text-transform: capitalize; 
    }

    .fullTable td, .fullTable th{
        border: 1px solid #ddd;
        padding: 8px;
    }
    
    .fullTable th{
        background-color: #ba9eafed;
        color: white;
    }

    .fullTablen tr:nth-child(even){
        background-color: rgb(0, 0, 0);
    }

    .fullTable tr:hover{
        background-color: #ddd;
    }

</style>

{% extends 'templates/../model-page.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">
<!-- Cabeçalho da página -->
  <div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
    <div class="col-auto">
      <img class="univesp-elos img-fluid rounded mx-auto my-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/evento2.svg" alt="Logo balões de festa Univesp e Elos de Amor" width="90px">
    </div>
    <div class="col-md-8 text-white">
      <h2 class="display-5 font-italic">Doadores</h1>
      <p class="lead">Veja os doadores.</p>
    </div>
  </div><!-- Fim do cabeçalho -->
<!-- Conteúdo Principal -->
  <div class="row justify-content-center mt-0">
    <div class="col-md-12 border-secondy justify-content-start">
        <div class="col-md-8 mx-auto">

            <div class="tableContainer">
                <table class="fullTable">
                    <thead>
                        <tr>                
                            <th>Nº</th>
                            <th>NOME</th>
                            <th>SOBRENOME</th>
                            <th>DATA DE NASCIMENTO</th>
                            <th>ENDEREÇO</th>
                            <th>Nº</th>
                            <th>COMPLEMENTO</th>
                            <th>CEL</th>
                            <th>DOADOR</th>               
                        </tr>
                    </thead>
                    <tbody>
                        {% for doadores in object_list %}
                        <tr>
                            <td>{{ doadores.id }}</td>
                            <td>{{ doadores.nome }}</td>
                            <td>{{ doadores.sobrenome }}</td>
                            <td>{{ doadores.dt_nasc }}</td>
                            <td>{{ doadores.endereco }}</td>
                            <td>{{ doadores.numero }}</td>
                            <td>{{ doadores.complemento }}</td>
                            <td>{{ doadores.celular }}</td>
                            <td>{{ doadores.username }}</td>
                        </tr>
                        {% empty %}
                    </tbody>
                    {% endfor %}
                </table>
            </div>

        </div>
    </div><!-- Fim row-->
  </div><!-- Fim do Conteúdo principal -->

</div>

{% endblock %}

apps/doadores/templates/doadores/formedit copy.html
{% extends 'templates/../home.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block rodape-links %}
{% endblock %}

{% block conteudo %}

<h3>Registros</h3>

<p class="lead">
    Atualize os campos caso necessário
</p>

<hr>

<form action="" method="POST">

    {% csrf_token %}

    {{ form.as_p }}

   
    <button type="submit" class="btn btn-success">Atualizar</button>

</form>


{% endblock %}