api/urls.py
from django.urls import include, path
from rest_framework import routers

#from api.views.carrega_parceiros import ParceirosViewSet
from .views import *

router = routers.DefaultRouter()
#router.register(r'',views.controleParceiros)
router.register('parceiros', ParceirosViewSet, basename='Parceiros')
router.register('eventos', EventosViewSet, basename='Eventos')
router.register(r'doadores', DoadoresViewSet, basename="Doadores")
router.register(r'doacao', DoacaoViewSet, basename="Doacao")
router.register('blog', PostViewSet, basename='Blog')

urlpatterns = [
    # path('', views.getData),
    # path('add/', views.addData)
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

apps/blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.carrega_posts, name='posts'),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/eventos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'eventos'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.carrega_eventos, name='eventos'),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/parceiros/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from parceiros.views import carrega_parceiros,carrega_parceiros2
from . import views

app_name = 'parceiros'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', carrega_parceiros, name='parceiros'),
    path('2', carrega_parceiros2, name='parceiros2'),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elos_be/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
import parceiros

from elos_be.views import carrega_abrigo, carrega_home, carrega_index, carrega_contatos, carrega_ajuda, carrega_resgate, PaginaHome

from cadastro import views
from eventos import urls, views
from parceiros import urls, views
from doadores import urls, views 

from django.views.generic import TemplateView

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import routers
from doadores.api import viewsets as doadoresviewsets

route = routers.DefaultRouter()

route.register(r'doadores', doadoresviewsets.DoadoresViewSet, basename="Doadores")
route.register(r'doacao', doadoresviewsets.DoacaoViewSet, basename="Doacao")

app_name = 'elos_be'
urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')), #ATIVAÇÃO DE RICH-TEXT
    path('', RedirectView.as_view(url='/elos/')),
    path('elos/', carrega_index, name="index"),
    path('elos/projeto', carrega_abrigo, name="projeto"),
    path('elos/contatos', carrega_contatos, name="contatos"),
    path('elos/ajuda', carrega_ajuda, name="ajuda"),
    path('elos/resgate', carrega_resgate, name="resgate"),
    path('elos/parceiros',include("parceiros.urls")),
    path('elos/eventos/', include("eventos.urls")),
    path('elos/mural_animais/', include("cadastro.urls")),
    path('elos/blog/', include("blog.urls")),
    path('elos/social/', include("rede_social.urls")),
    path('home/', PaginaHome.as_view(), name='home'),
    path('home2/', carrega_home, name='home2'),
    # path('home/', carrega_aplicacao, name="home"),
    path('', include("login_users.urls")),
    path('doadores', include("doadores.urls")),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include(route.urls)),
    # path('api-auth/', include('rest_framework.urls')),
    
]

templates/_alerts.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/abrigo.html
{% extends 'templates/../model-page.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
<!-- Cabeçalho da página -->
  <div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
    <div class="col-auto">
      <img class="univesp-kaotinho img-fluid rounded mx-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/univesp-kaotinho.png" alt="Univesp e Elos de Amor" width="300px">
    </div>
    <div class="col-md-8 text-white">
      <h2 class="display-5 font-italic">Elos de Amor e alunos UniVESP</h1>
      <p class="lead">Saiba mais como surgiu essa parceria.</p>
    </div>
  </div><!-- Fim do cabeçalho -->
<!-- Conteúdo Principal -->
  <div class="row justify-content-center">
    <div class="col-md-8 border-secondy">
      <ul class="nav nav-tabs border-secondy" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="univesp-tab" data-bs-toggle="tab" data-bs-target="#univesp" type="button" role="tab" aria-controls="univesp" aria-selected="true">A Universidade</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pi-tab" data-bs-toggle="tab" data-bs-target="#pi" type="button" role="tab" aria-controls="pi" aria-selected="false">O projeto</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="kaotinho-tab" data-bs-toggle="tab" data-bs-target="#kaotinho" type="button" role="tab" aria-controls="kaotinho" aria-selected="false">Elos de Amor</button>
        </li>
      </ul>
      <div class="tab-content p-3 border-secondary shadow" id="myTabContent">
        <div class="tab-pane fade show active justify-content-between" id="univesp" role="tabpanel" aria-labelledby="univesp-tab">
          <h3 class="fs-3">A UniVESP</h3>
          <p class="text-xs-right"">A Universidade Virtual do Estado de São Paulo (Univesp) é a quarta universidade pública paulista, exclusivamente de educaçao à distância. E tem por objetivo o ensino, a pesquisa e a extensão, obedecendo ao princípio de sua indissociabilidade, integrados pelo conhecimento como bem público. Ela se constitui como universidade dedicada à formação de educadores – para a universalização do acesso à educação formal e à educação para cidadania, assim como a de outros profissionais comprometidos com o bem-estar social e cultural da população.</p>
          <h3 class="fs-3">Principais parceiros</h3>
          <p>Entre seus principais parceiros destacam-se a  Universidade de São Paulo (USP), Universidade Estadual Paulista (UNESP), Universidade Estadual de Campinas (UNICAMP) e Centro Paula Souza (CPS).</p>
          <a href="https://univesp.br/" target="_blank">Fonte: Site UniVESP</a>
        </div>
        <div class="tab-pane fade" id="pi" role="tabpanel" aria-labelledby="pi-tab">
          <h3 class="fs-3">A Disciplina</h3>
          <p>A disciplina "Projeto Integrador", trata-se de uma atividade curricular obrigatória que consiste na resolução de um problema real contextualizado na profissão em que o curso está inserido.</p>
          <p>Em grupo, os estudantes devem delimitar um problema a partir do tema norteador da disciplina, propondo uma solução aplicável, usando os conhecimentos estudados nas disciplinas cursadas até o momento.</p>
          <a href="https://apps.univesp.br/o-que-e-projeto-integrador/" target="_blank">Fonte: REA</a>
          <h3 class="fs-3">O Tema</h3>
          <p>Desenvolver um software com framework web (Django) que utilize banco de dados (PostgreSQL), inclua script web (Javascript), nuvem, uso de API (Django REST-API), acessibilidade, controle de versão (git e gitHUB) e testes. Opcionalmente, incluir análise de dados.</p>
          <h3 class="fs-3">O grupo</h3>
          <p>Os alunos, Bruno Caldas de Souza, Eduardo Cabral de Souza e Vinícius Gomes Barbosa, do Eixo Computação - Turma 2020 entraram em contato com algumas instituições. E adotaram a causa e o desafio apresentado pelo Projeto Kãotinho.</p>
          <iframe class="img-fluid" width="560" height="315" src="https://www.youtube.com/embed/wfxonQk92bQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="tab-pane fade" id="kaotinho" role="tabpanel" aria-labelledby="kaotinho-tab">
          <h3 class="fs-3">O que é o projeto Elos de Amor?</h3>
          <p>É um projeto de proteção, cujo objetivo é resgatar e recuperar animais abandonados ou que estejam sofrendo maus-tratos.</p>
          <p>O objetivo maior do projeto é ajudar pessoas carentes e/ou em situação financeira dificil, com o emprestimo sem onus(comodato) de equipamentos e/ou utensilios pertecentes ao elos de amor que necessitem, o tempo que precisar, devolvendo ao projeto, onde passará por uma devida manutenção e higienização ficando disponivel para outras pessoas.</p>
          <p>Este carater multiplicador fará que alcancemos um universo maior de pessoas atendidas sem um aumento significativos de custos.</p>
          <p>Partindo da doação de pessoas que poderão até indicar as pessoas para receberem o bem, seguindo as normas do projeto, serão classificadas como doador e automaticamente receberão mensagens de agradecimento do receptor do bem, após o uso e seu conseguente retorno, este receptor passará automaticamente para ser um doador.</p>
          <p>Em sintese seria conectar pessoas que tem ou queira doar algo para outras pessoas que necessitem e não tem condições de adquirir.</p>
          <p>A primeira cadeira doada ao projeto já atendeu a duas pessoas e já retornou estando disponivel para atender a uma terceira pessoa.</p>
          <h3 class="fs-3">Como Surgiu?</h3>
          <p>Recebi de uma amiga chamada MARTA, uma mensagem onde perguntava se eu não conhecia alguém para doar uma cadeira de rodas, por que ela chorando, informou que teve que carregar suas mãe nas costas para uma consulta no IMIP – INSTITUTO MARTENO INFANTIL DO ESTADO DE PERNAMBUCO, e eu a questionei, dizendo que a instituição tinha cadeiras de rodas disponíveis para este traslado da entrada até suas dependências e a mesma me informou que as cadeiras disponíveis não eram suficientes para atender toda a demanda. Ela também me informou que pesquisou na OLX para comprar, mas o preço era alto para as suas condições.</p>
          <p>A informei que não sabia de ninguém que tivesse uma cadeira e que colocaria a sua mensagem no grupo de intercessores e o outros grupos, além dos meus contatos, isto por volta das 07:00 da manhã do dia 27/11/2021 da minha consulta oftalmológica com o Dr. Marcos Matos do HOSPITAL HVISÃO, que foi uma das pessoas que enviei a mensagem, terminada a consulta eu e minha esposa fomos almoçar no SHOPPING RIO MAR e após o almoço fui ao sanitário e quando entrei ECOOU NA MINHA MENTE: NÃO FIQUE SÓ EM MARTA!</p>
          <p>Fui para o meu trabalho e as 15:00 horas ao ver as mensagens, encontro a do meu amigo Rui Mesquita perguntando se eu tenho a quem doar duas muletas, entendi como uma resposta de DEUS para mim e já pensando em receber cadeiras quebradas, conserta-las e doar em COMODATO (EMPRESTIMO POR TEMPO INDETERMINADO E SEM COBRANÇA DE VALORES, COM A DEVOLUÇÃO QUANDO NÃO MAIS PRECISAR DO BEM) para as pessoas que não tem condições de comprar, liguei para ROBSON, presidente da COOPERATIVA DE CATADORES DO BREJO DE BEBERIBE - RESGATANDO VIDAS, a qual ajudei a registrar, o informando que toda a cadeira de rodas quebrada guardasse para mim e lhe falei do projeto e para minha surpresa ele me informou que tinha uma cadeira de rodas em condições de uso para doar, pedi para ele me mandar as fotos da cadeira, enviei para MARTA informando que ela teria que ter o cuidado de higienizar a cadeira, trocar forro, etc. Ela informou que queria a cadeira.</p>
          <p>Há noite, por volta das 21:00 horas li a mensagem do DR. MARCOS MATOS dizendo: AMORIM eu sei o sofrimento dessa pessoa, já passei por isso e pude comprar a cadeira, quero fazer a doação de duas cadeiras.</p>
          <p>No outro dia as 10:00 horas MARTA recebeu a cadeira doada, ajeitou, higienizou mas infelizmente a sua quis usar a cadeira, foi doada a outra pessoa que a utilizou e já devolveu, estando disponível para outra pessoa, este PROCESSO MULTIPLICADOR que o nosso projeto pretender atingir o maior numero de pessoas não deixando que nenhuma pessoa que nos procure seja atendida, pois contamos com os nossos patronos SÃO PIO DE PIERTRICINA e SANTA DULCE DOS POBRE intercedendo a DEUS por todos nos. </p>
          <iframe class="img-fluid" width="560" height="315" src="" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div>
            <a class="btn btn-secondary" href="{% url 'ajuda' %}" role="button">Como ajudar?</a>
            <a class="btn btn-secondary" href="{% url 'contatos' %}" role="button">Contatos e Redes Sociais</a>
          </div>
        </div>
      </div>
    </div>  
  </div><!-- Fim do Conteúdo principal -->

</div>

{% endblock %}

templates/ajuda.html
{% extends 'templates/../model-page.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
<!-- Cabeçalho da página -->
  <div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
    <div class="col-auto">
      <img class="univesp-elos img-fluid rounded mx-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/ajuda3.svg" alt="Univesp e Elos de Amor" width="90px">
    </div>
    <div class="col-md-8 text-white">
      <h2 class="display-5 font-italic">Como ajudar?</h1>
      <p class="lead">Confira como apoiar nosso projeto.</p>
    </div>
  </div><!-- Fim do cabeçalho -->
<!-- Corpo do site -->
  <div class="row justify-content-center mt-0">
    <div class="col-md-8 border-secondy justify-content-start">
      <div class="acoordion" id="acoordion-ajuda">
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-heading-ajuda">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-ajuda" aria-expanded="true" aria-controls="flush-collapse-ajuda">
              Como posso ajudar?
            </button>
          </h2>
          <div id="flush-collapse-ajuda" class="accordion-collapse collapse show" aria-labelledby="flush-heading-ajuda" data-bs-parent="#acoordion-ajuda">
            <div class="accordion-body">
              <stron>A sua ajuda é muito importante, essencial e necessária, nos necessitamos de braços, transportes, do seu conhecimento, sim do seu conhecimento para nos orientar, coloque a sua experiencia profissional em colaboração conosco e multiplique os talentos que DEUS te deu como está em Mateus 25,29 e multiplique o números de pessoas assistidas,  o que não pode é deixar a sua solidariedade de fora do ELOS DE AMOR.</stron>
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-heading-parceiro">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-dinheiro" aria-expanded="false" aria-controls="flush-collapse-dinheiro">
              Seja nosso parceiro!
            </button>
          </h2>
          <div id="flush-collapse-dinheiro" class="accordion-collapse collapse" aria-labelledby="flush-heading-dinheiro" data-bs-parent="#acoordion-ajuda">
            <div class="accordion-body">
              <stron>
                <p>EMPRESÁRIO seja nosso parceiro contribuindo com equipamentos, transporte, logística, pessoal, participando ativamente conosco e acompanhando todo o processo e transparência e se possível também financeiramente.</p>
              <p>UNIVERSITÁRIO venha conhecer e fazer parte da solidariedade ao próximo e transforme a sua visão do mundo, para um com mais amor.</p>
              <p>DOAÇÃO FINANCEIRA a sua contribuição financeira ajuda a multiplicar as pessoas assistidas, venha fazer parte da nossa família, associando-se como benfeitor desta obra.</p>
              <p>ESPAÇO FISICO necessitamos de um local para a manutenção, guarda, controle e logística para a entrega e recolhimento quando necessário, das doações, visitas, etc.</p>
              </stron>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/contatos.html
{{% extends 'templates/../model-page.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <!-- Cabeçalho da página -->
      <div class="row justify-content-center jumbotron jumbotron-fluid bg-secondary mt-4 py-4">
        <div class="col-auto">
          <img class="univesp-elos img-fluid rounded mx-auto d-block" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/ajuda3.svg" alt="Univesp e Elos de Amor" width="90px">
        </div>
        <div class="col-md-8 text-white">
          <h2 class="display-5 font-italic">Nossos contatos</h1>
          <p class="lead">Confira nossos contatos.</p>
        </div>
      </div><!-- Fim do cabeçalho -->
    <!-- Corpo do site -->
    <div class="row justify-content-center mt-0">
        <div class="col-md-8 border-secondy justify-content-start align-middle">
          <p>
            <a href="http://api.whatsapp.com/send?phone=5581988976769" target="_blank">
              <i class="fa fa-whatsapp" style="font-size:48px;"></i> +5581988976769
            </a>
          </p>
          <p>
            <a href="mailto:elosdeamor.rede@gmail.com?subject=Contato: Elos de Amor">
              <i class="material-icons" style="font-size:48px;">email</i> elosdeamor.rede@gmail.com
            </a>
          </p>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'model-page.html' %}
{% load static %}

{% block content %}
<!-- Carrossel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="first-slide univesp-elos img-carrossel img-fluid" src="https://piunivesp.s3.sa-east-1.amazonaws.com/elos_de_amor/media/elos_univesp.png" alt="Primeiro Slide"> 
      <div class="container">
        <div class="carousel-caption text-right d-sd-block">
          <p>Elos de Amor e UniVESP</p>
          <p>
            <a class="btn btn-lg btn-secondary" href="{% url 'projeto' %}" role="button">Saiba mais</a>
          </p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block h-100 w-100 d-inline-block img-carrossel img-fluid" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/parceiros3.svg" alt="Segundo Slide">
      <div class="container">
        <div class="carousel-caption text-left d-sd-block">
          <p>Nossos Parceiros</p>
          <p>
            <a class="btn btn-lg btn-secondary" href="{% url 'parceiros:parceiros' %}" role="button">Confira</a>
          </p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block h-100 w-100 d-inline-block img-carrossel" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/eventos3.svg" alt="Terceiro Slide">
      <div class="container">
        <div class="carousel-caption text-right d-sd-block">
          <p>Projetos e Eventos</p>
          <p>
            <a class="btn btn-lg btn-secondary" href="{% url 'eventos:eventos' %}" role="button">Participe</a>
          </p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Próximo</span>
  </a>
</div> <!--Fim Carrossel -->
<!-- Conteúdo Principal do site -->
<div class="container marketing">
  <!-- Três colunas de texto -->
  <div class="row">
    <div class="col-lg-4">
      <img class="rounded-circle" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/ajuda1.png" alt="ajuda" width="140" height="140">
      <h2>Como ajudar?</h2>
      <p>Precisamos de você, verifique como ajudar.</p>
      <p><a class="btn btn-secondary" href="{% url 'ajuda' %}" role="button">Mais detalhes »</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="rounded-circle" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/resgate1.png" alt="resgate" width="140" height="140">
      <h2>Blog Elos de Amor</h2>
      <p>Confira nosso blog com dicas e sugestões.</p>
      <p><a class="btn btn-secondary" href="{% url 'blog:posts' %}" role="button">Mais detalhes »</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="rounded-circle" src="https://piunivesp.s3.sa-east-1.amazonaws.com/media/contato1.png" alt="contato" width="140" height="140">
      <h2>Nossos contatos</h2>
      <p class="marketing">Confira nossos contatos.</p>
      <p class="marketing"><a class="btn btn-secondary" href="{% url 'contatos' %}" role="button">Mais detalhes »</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->
</div>
{% endblock %}

templates/model-footer.html
{% load static %}

<div class="container">
  <div class="row navbar navbar-nav bg-white p-0  fixed-bottom">
    <div class="col">
      <span class="nav-item d-none d-md-block fs-6 fw-lighter align-middle text-center">
        Desenvolvido pelos alunos da UniVESP - Turma 2020 na disciplina de Projeto Integrador II
      </span>
    </div>
    <div class="col">
      <span class="nav-item fs-6 fw-lighter align-middle text-center p-0">
        <a class="nav-link" href="#">Voltar ao topo</a>
      </span>
    </div>
  </div>
</div>

templates/model-navbar.html
{% load static %}
<!-- Barra de navegação -->
<nav class="fixed-top navbar navbar-expand-lg navbar-light bg-white shadow justify-content-center m-0 px-0 py-0">
  <div class="container mx-2">
    <!-- Logo e Título do site -->
    <a class="navbar-brand h1 mb-8" href="{% url 'index' %}">
        <img src="https://piunivesp.s3.sa-east-1.amazonaws.com/elos_de_amor/media/logo-elos_transparente.png" width="50" height="50" class="d-inline-block align-middle m-0 px-0 py-0" alt="logo Elos de Amor">
        <spam class="align-middle" id="titulo">Elos de Amor</spam>
    </a><!-- Fim logo e título-->
    <!-- Botão collased -->
    <button class="navbar-toggler m-0 p-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button><!-- Fim botão -->
    <!-- Menu -->  
    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">Elos</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'parceiros:parceiros' %}">Parceiros</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'eventos:eventos' %}">Projetos e Eventos</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'blog:posts' %}">Blog</a></li>
      </ul>
      <!-- Cadastro  -->
      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      
        <li class="nav-item dropdown"   id="navDropDownLogado">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="navDropDownLinkUser">
            <span id="username">{{ request.user }}</span>
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'home' %}" id="navDropDownLinkHome">Home</a>
            <a class="dropdown-item" href="{% url 'formc' %}" id="navDropDownLinkPerfil">Dados Pessoais</a>
            <a class="dropdown-item" href="{% url 'ldoacao' %}" id="navDropDownLinkDonativos">Todos os Donativos</a>
            <a class="dropdown-item" href="{% url 'novadoacao' %}" id="navDropDownLinkAddDoacao">Nova Doação</a>
            <a class="dropdown-item" href="{% url 'formup' %}" id="navDropDownLinkAtualizaPerfil">Atualiza Perfil</a>
            {% if user.is_superuser %}
                <!--<a class="dropdown-item" href="{% url 'home' %}">Home</a>-->
                <a class="dropdown-item" href="{% url 'listar' %}" id="navDropDownLinkAllDoadores">Listar Doadores</a>
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'logout' %}">
              Sair
            </a>
          </div>
        </li>
      {% else %}
        <li class="nav-item dropdown" id="navDropDownNaoLogado">
          <a class="nav-link dropdown-toggle" href="#" id="navDropDownLinkMenu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'login' %}"  id="navDropDownLinkLogin" >
              Login
            </a>
            <a class="dropdown-item" href="{% url 'cep' %}"  id="navDropDownLinkInscreva" >
              Inscreva-se
            </a>
          </div>
        </li>
      {% endif %}
      </ul>
    </div><!-- Fim Menu -->
  </div>
</nav>